library(readr)
#Reading the file generated by pyhton code
link <- read_delim("C:/Users/Ravali/Desktop/asker_answerer.tsv", 
                      "\t", escape_double = FALSE, trim_ws = TRUE)

#library to plot
library(igraph)
#data frame is assigned to network with the directed links
network <- graph_from_data_frame(d=link, directed=T) 

#Plotting is done with 'fruchterman.reingold' layout
plot(network,vertex.size = 2,vertex.color = 'yellow',edge.width = 1,
     edge.color = 'black',edge.arrow.size=.02, vertex.label = NA, 
     layout = layout.fruchterman.reingold,main = "Asker-Answerer Plot")

library(CINNA)
#Gaint link from above plotted network is assigned to com
com<-giant_component_extract(network,directed = TRUE)
#user id's in the giant network is sent to giant 
giant<-data.frame(
  asker=com[2][[1]][,1],
  answer=com[2][[1]][,2])

#data frame is assigned to g_network with the directed links
g_network<-graph_from_data_frame(d=giant, directed=T)

#Plotting is done with 'fruchterman.reingold' layout
plot(g_network,vertex.size = 3,vertex.color = 'yellow',edge.width = 1,
     edge.color = 'black',edge.arrow.size=.04, vertex.label = NA, 
     layout = layout.fruchterman.reingold,main = "Giant Component")

#Output file is generated in .tsv
write.table(g_network, file='giant_component.tsv', quote=FALSE, sep='\t', col.names = NA)
